"""Initial tenant, identity, store assignment, and audit schema."""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_tenants"
down_revision = None
branch_labels = None
depends_on = None


TABLES = (
    "tenants",
    "users",
    "memberships",
    "stores",
    "store_memberships",
    "audit_events",
)
TENANT_TABLES = ("memberships", "stores", "store_memberships", "audit_events")
# Trust boundary: app.tenant_id is a caller-settable PostgreSQL custom setting.
# These policies constrain SQL generated by the trusted application transaction
# helper; possession of the raw wso_app SQL role is not tenant isolation.
# Production gate: replace this predicate on every business table with a
# database-verified, transaction-bound scope claim (or remove direct table
# grants and expose only narrowly scoped functions). The adversarial live test
# test_raw_app_role_cannot_forge_tenant_context_release_gate must pass first.
TENANT_EXPRESSION = (
    "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"
)


def _roles() -> None:
    for role in ("wso_migrator", "wso_app", "wso_identity_bootstrap"):
        op.execute(
            f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') "
            f"THEN CREATE ROLE {role} LOGIN NOINHERIT NOSUPERUSER NOCREATEDB "
            "NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF; END $$"
        )
        op.execute(
            f"ALTER ROLE {role} LOGIN NOINHERIT NOSUPERUSER NOCREATEDB "
            "NOCREATEROLE NOREPLICATION NOBYPASSRLS"
        )
    op.execute(
        "DO $$ BEGIN IF EXISTS ("
        "SELECT 1 FROM pg_auth_members AS grant_edge "
        "JOIN pg_roles AS member_role ON member_role.oid = grant_edge.member "
        "WHERE member_role.rolname IN ('wso_app', 'wso_identity_bootstrap')"
        ") THEN RAISE EXCEPTION 'runtime role membership is forbidden'; "
        "END IF; END $$"
    )
    op.execute("GRANT USAGE ON SCHEMA public TO wso_app, wso_identity_bootstrap")


def _rls(table: str, *, expression: str = TENANT_EXPRESSION) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY {table}_tenant_policy ON {table} TO wso_app "
        f"USING ({expression}) WITH CHECK ({expression})"
    )


def upgrade() -> None:
    _roles()
    op.create_table(
        "tenants",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("oidc_issuer", sa.String(255), nullable=False),
        sa.Column("oidc_subject", sa.String(255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "oidc_issuer", "oidc_subject", name="uq_users_oidc_principal"
        ),
    )
    op.create_table(
        "memberships",
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            primary_key=True,
        ),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "role IN ('OWNER', 'MANAGER', 'STAFF')", name="ck_memberships_role"
        ),
    )
    op.create_index("ix_memberships_user_id", "memberships", ["user_id"])
    op.create_table(
        "stores",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("timezone", sa.String(64), nullable=False),
        sa.Column(
            "active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_stores_tenant_id_id"),
    )
    op.create_index("ix_stores_tenant_active", "stores", ["tenant_id", "active"])
    op.create_table(
        "store_memberships",
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("store_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "store_id"],
            ["stores.tenant_id", "stores.id"],
            name="fk_store_memberships_tenant_store",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["memberships.tenant_id", "memberships.user_id"],
            name="fk_store_memberships_tenant_user",
        ),
    )
    op.create_index(
        "ix_store_memberships_tenant_user",
        "store_memberships",
        ["tenant_id", "user_id"],
    )
    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id"),
            nullable=False,
        ),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True)),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True)),
        sa.Column("correlation_id", sa.String(100)),
        sa.Column("result", sa.String(100), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_user_id"],
            ["memberships.tenant_id", "memberships.user_id"],
            name="fk_audit_events_tenant_actor",
        ),
    )
    op.create_index(
        "ix_audit_events_tenant_occurred", "audit_events", ["tenant_id", "occurred_at"]
    )

    for table in TABLES:
        op.execute(f"REVOKE ALL ON {table} FROM PUBLIC")
    _rls(
        "tenants",
        expression="id = nullif(current_setting('app.tenant_id', true), '')::uuid",
    )
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE users FORCE ROW LEVEL SECURITY")
    for table in TENANT_TABLES:
        _rls(table)

    op.execute(
        "CREATE POLICY users_identity_policy ON users FOR SELECT TO wso_identity_bootstrap "
        "USING (oidc_issuer = current_setting('app.oidc_issuer', true) "
        "AND oidc_subject = current_setting('app.oidc_subject', true))"
    )
    op.execute(
        "CREATE POLICY memberships_identity_policy ON memberships FOR SELECT TO wso_identity_bootstrap "
        "USING (user_id IN (SELECT id FROM users WHERE "
        "oidc_issuer = current_setting('app.oidc_issuer', true) "
        "AND oidc_subject = current_setting('app.oidc_subject', true)))"
    )
    op.execute(
        "GRANT SELECT ON tenants, memberships, stores, store_memberships, audit_events TO wso_app"
    )
    op.execute("GRANT INSERT, UPDATE, DELETE ON stores, store_memberships TO wso_app")
    op.execute("GRANT INSERT ON audit_events TO wso_app")
    op.execute(
        "GRANT SELECT (id, oidc_issuer, oidc_subject) ON users TO wso_identity_bootstrap"
    )
    op.execute(
        "GRANT SELECT (tenant_id, user_id, role) ON memberships TO wso_identity_bootstrap"
    )
    for table in TABLES:
        op.execute(
            f"CREATE POLICY {table}_migration_policy ON {table} "
            "TO wso_migrator USING (true) WITH CHECK (true)"
        )
    op.execute("GRANT USAGE, CREATE ON SCHEMA public TO wso_migrator")
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} OWNER TO wso_migrator")
    op.execute(
        "CREATE FUNCTION public.wso_validate_tenant_authorization("
        "p_tenant_id uuid, p_user_id uuid, p_role text) RETURNS boolean "
        "LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog "
        "AS $wso$ DECLARE current_role text; BEGIN "
        "IF p_tenant_id IS NULL OR p_user_id IS NULL OR p_role IS NULL "
        "OR p_tenant_id IS DISTINCT FROM "
        "nullif(current_setting('app.tenant_id', true), '')::uuid "
        "THEN RETURN false; END IF; "
        "SELECT membership.role INTO current_role FROM public.memberships AS membership "
        "WHERE membership.tenant_id = p_tenant_id AND membership.user_id = p_user_id "
        "FOR SHARE; RETURN coalesce(current_role = p_role, false); END; $wso$"
    )
    op.execute(
        "ALTER FUNCTION public.wso_validate_tenant_authorization(uuid, uuid, text) "
        "OWNER TO wso_migrator"
    )
    op.execute(
        "REVOKE ALL ON FUNCTION public.wso_validate_tenant_authorization(uuid, uuid, text) "
        "FROM PUBLIC"
    )
    op.execute(
        "GRANT EXECUTE ON FUNCTION public.wso_validate_tenant_authorization(uuid, uuid, text) "
        "TO wso_app"
    )


def downgrade() -> None:
    op.execute(
        "DROP FUNCTION public.wso_validate_tenant_authorization(uuid, uuid, text)"
    )
    for table in reversed(TABLES):
        op.drop_table(table)
    # Roles are environment identities; their lifecycle is outside schema rollback.
